# -*- Makefile -*-

SRCS	=	push_swap.c \
			parsing.c

NAME	=	../push_swap
CC		=	cc
CFLAGS	=	-Wall -Wextra -Werror -I
INC_DIR	=	../includes
LIBFT	=	../libft.a

all:
	@$(CC) $(CFLAGS) $(INC_DIR) $(SRCS) $(LIBFT) -o $(NAME)
	@echo Mandatory is compiled.

